### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by jjh4450** [bluedisk/hangul-toolkit#4]
파이썬 `3.11` `venv`를 기반으로 사용하던 중 다음과 같은 오류가 발생했습니다.
six를 설치하여 해결했으나 추가적으로 배포 과정에서 조치가 필요할 거 같아 문의 드립니다.

```py
Traceback (most recent call last):
  File ...
    import hgtk
  File "my_path\.venv\Lib\site-packages\hgtk\__init__.py", line 6, in <module>
    from . import checker
  File "my_path\.venv\Lib\site-packages\hgtk\checker.py", line 6, in <module>
    from . import letter as lt
  File "my_path\.venv\Lib\site-packages\hgtk\letter.py", line 6, in <module>
    from six import unichr
ModuleNotFoundError: No module named 'six'
```

**Comment by bluedisk** [comment]
제보 감사합니다! 바로 조치하겠습니다!
